# Generated by Django 2.1.7 on 2019-03-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10)),
                ('price', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('cloth', models.CharField(choices=[('party', 'party_wear'), ('casual', 'casual_wear')], max_length=10)),
            ],
        ),
    ]
