# Generated by Django 2.1.7 on 2019-03-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_vender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green')], default=False, max_length=10),
        ),
    ]
