# Generated by Django 2.1.7 on 2019-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('White', 'White'), ('red', 'Red'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Green', 'Green')], default=False, max_length=10),
        ),
    ]
