# Generated by Django 2.1.7 on 2019-03-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190320_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('navyblue', 'Navyblue'), ('grey', 'Grey')], default=False, max_length=10),
        ),
    ]
