# Generated by Django 2.1.7 on 2019-03-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('email', models.EmailField(default=False, max_length=254)),
                ('address', models.CharField(default=False, max_length=40)),
                ('shop_name', models.CharField(max_length=40)),
            ],
        ),
    ]
